[features]
seeds = false
skip-lint = false
[programs.devnet]
russian_roulette = "iyvFKe3NuJEpKVuPznNJQUUDiFt4Ho9UZefe3RHVnrm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "VRFzZoJdhFWL8rkvu87LpKM3RbcVezpMEc6X5GVDr7y"
program = "../../../js/dist/orao_vrf.so"
